language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker
  
cleanup: true

before_install:
  - mvn package
  - docker build -t koolbeep/devworks .
  
#script:
#  - docker run -e CI=true koolbeep/devworks

deploy:
  skip_cleanup: true
  zip_file: "target/devworks-1.0.0.jar"
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "devWorks"
  env: "devworks-test"
  bucket_name: "elasticbeanstalk-us-east-2-548571153351"
  bucket_path: "devWorks"
  on:
    branch: master
  access_key_id: $AWS_DEVWORKS_ACCESS_KEY
  secret_access_key: $AWS_DEVWORKS_SECRET_KEY

  
 
