language: java

jdk:
  - openjdk8

sudo: required

services:
  - docker

before_install:
  - mvn package
  - docker build -t koolbeep/devworks .

deploy:
  skip_cleanup: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "devworkjava3"
  env: "Devworkjava3-env"
  bucket_name: "elasticbeanstalk-us-east-2-548571153351"
  bucket_path: "devworkjava3"
  zip_file: "target/devworks-1.0.0.jar"
  on:
    branch: master
  access_key_id: $AWS_DEVWORKS_ACCESS_KEY
  secret_access_key: $AWS_DEVWORKS_SECRET_KEY
  
 
